### ISSUE TITLE
don't run on windows10 Japanese

### ISSUE THREAD

**Issue by kongou-ae** [kongou-ae/textlint-plugin-asciidoc#1]
```
C:\Hugo\aimless.jp [master ≡ +11 ~3 -4 !]> .\node_modules\.bin\textlint .\test0.adoc
× Error
Cannot read property 'join' of null

× Stack trace
TypeError: Cannot read property 'join' of null
    at Date.ːzone (C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\node_modules\asciidoctor.js\node_modules\opal-runtime\src\opal.js:17861:62)
    at C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\node_modules\asciidoctor.js\node_modules\opal-runtime\src\opal.js:18049:28
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Date.ːstrftime (C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\node_modules\asciidoctor.js\node_modules\opal-runtime\src\opal.js:17912:21)
    at $Document.ːinitialize (C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\node_modules\asciidoctor.js\dist\asciidoctor.js:27367:58)
    at singleton_class_alloc.TMP_4 [as $new] (C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\node_modules\asciidoctor.js\node_modules\opal-runtime\src\opal.js:3139:23)
    at module_constructor.ːload (C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\node_modules\asciidoctor.js\dist\asciidoctor.js:33226:43)
    at module_constructor.Opal.Asciidoctor.$$class.$$proto.load (C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\node_modules\asciidoctor.js\dist\asciidoctor.js:33467:15)
    at parse (C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\lib\asciidoc-to-ast.js:147:27)
    at preProcess (C:\Hugo\aimless.jp\node_modules\textlint-plugin-asciidoc\lib\AsciidocProcessor.js:26:53)
    at TextlintCore._parallelProcess (C:\Hugo\aimless.jp\node_modules\textlint\lib\textlint-core.js:205:23)
    at C:\Hugo\aimless.jp\node_modules\textlint\lib\textlint-core.js:270:31
    at tryCatcher (C:\Hugo\aimless.jp\node_modules\textlint\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Hugo\aimless.jp\node_modules\textlint\node_modules\bluebird\js\release\promise.js:510:31)
C:\Hugo\aimless.jp [master ≡ +11 ~3 -4 !]>
```

**Comment by kongou-ae** [comment]
if the output of `new Date().toString()` on your enviroment is as below, please change `opal.js` from before to after.

```
Tue Jan 03 2017 21:02:45 GMT+0900 (東京 (標準時))
```


before

```
      if (string.indexOf('(') == -1) {
        result = string.match(/[A-Z]{3,4}/)[0];
      }
      else {
        result = string.match(/\([^)]+\)/)[0].match(/[A-Z]/g).join('');
      }
```

after

```
      if (string.indexOf('(') == -1) {
        result = string.match(/[A-Z]{3,4}/)[0];
      }
      else {
        result = "JST";
      }
```
